Added CacheKeyGenerator
php-http/cache-plugin pull request #35
Opened 2017-03-31 15:13 UTC by Nyholm

This will fix #30

2017-03-31 15:59 UTC, Nyholm commented
Im done with this PR now. It is ready for review. 

PS: The commit "Support PSR-4" was a typo. I ment to write "Support PHP 5.4"

2017-03-31 19:33 UTC, Nyholm commented on src/CachePlugin.php
> +            'cache_key_generator' => null,
Not sure if I should use null here or if I should instanciate the default generator. Using null will make sure we do not instanceiate unneeded objects.

2017-03-31 20:51 UTC, sagikazarmark requested changes
I had a few small comments, but looks ok. My fear is that we are putting too much logic here. Do you think the caching logic could be used elsewhere too? If so, should we extract it and move it to message for example?

2017-03-31 20:51 UTC, sagikazarmark commented on src/CachePlugin.php
> +        if (null === $this->config['cache_key_generator']) {
I would move this check right after the option resolution. I don't see any benefit in timing here, this will be resolved sooner or later.

2017-03-31 20:51 UTC, sagikazarmark commented on src/Generator/RequestLineAndBodyGenerator.php
> +class RequestLineAndBodyGenerator implements CacheKeyGenerator
Can we find a shorter name for this?

2017-03-31 20:51 UTC, sagikazarmark commented on spec/CachePluginSpec.php
> +use Http\Client\Common\Plugin\Generator\RequestLineAndBodyGenerator;
Hm, maybe put this under `...\Plugin\Cache\...`

2017-03-31 20:55 UTC, Nyholm commented on src/Generator/RequestLineAndBodyGenerator.php
> +class RequestLineAndBodyGenerator implements CacheKeyGenerator
Yes please! Any suggestions!

2017-03-31 21:48 UTC, Nyholm commented
Thank you for the feedback. I've updated. I renamed the generator to "SimpleGenerator" since it uses an naive approach. 

>My fear is that we are putting too much logic here. Do you think the caching logic could be used elsewhere too? If so, should we extract it and move it to message for example?

The `CachePlugin` is pretty fat, yes. One could refactor it to more helper classes and strategies. 

Im not sure it make sense to try to reuse the cache logic. Not at this point, because the code it too coupled to this specific use case. But I will not close that door forever. 

If I recall correctly we decided to not have cache logic in message because we did not want to have so many external dependencies in php-http/message. But you may be referring to the HTTP specific parts... Again, not sure.

I think we can let this library grow and mature. It is an implementation (and not an abstraction like most of our other libraries) so it is fine to bump it to 2.x and 3.x when we see a need for it.

2017-04-03 06:37 UTC, dbu approved these changes
i like this and think its fine to put in here at least for now. lets improve the cache plugin and if we realize we need the cache key elsewhere we can always push it upstream in a BC way as the cache depends on client-common

2017-04-03 06:42 UTC, Nyholm commented
Thank you for the reviews.

2017-04-03 06:42 UTC, merged

2017-04-03 06:52 UTC, dbu commented
please add documentation for this. i created https://github.com/php-http/documentation/issues/187 so we don't forget.

2017-04-03 07:02 UTC, Nyholm commented
Thank you