Update composer.json
php-http/cache-plugin pull request #86
Opened 2023-05-30 11:58 UTC by tacman

use the recommended package, fixes #85

| Q               | A
| --------------- | ---
| Bug fix?        | no|yes
| New feature?    | no|yes
| BC breaks?      | no|yes
| Deprecations?   | no|yes
| Related tickets | fixes #X, partially #Y, mentioned in #Z
| Documentation   | if this is a new feature, link to pull request in https://github.com/php-http/documentation that adds relevant documentation
| License         | MIT

#### What's in this PR?

Explain what the changes in this PR do.

#### Why?

Which problem does the PR fix? (remove this section if you linked an issue above)

#### Example Usage

``` php
// If you added new features, show examples of how to use them here
// (remove this section if not a new feature)

$foo = new Foo();

// Now we can do
$foo->doSomething();
```

#### Checklist

- [ ] Updated CHANGELOG.md to describe BC breaks / deprecations | new feature | bugfix
- [ ] Documentation pull request created (if not simply a bugfix)

#### To Do

- [ ] If the PR is not complete but you want to discuss the approach, list what remains to be done here

2023-05-31 12:04 UTC, dbu requested changes
thanks for the pull request. we already support PSR-17 in the cache class.

the problem is that for bootstrapping, one has to pass an implementation of either the PSR-17 or the legacy php-http factory. 

i think to avoid hickups for the users, the best is to start a new major version of the cache plugin that requires a psr-17 implementation and no php-http/message-factory anymore and also does not allow the legacy anymore, so that we can declare types strictly again.

do you want to change the code accordingly? you will need to add an actual psr-17 implementation to require-dev and instantiate that in the tests. i suggest `nyholm/psr7`

2023-05-31 12:04 UTC, dbu commented on composer.json
> +        "psr/http-factory": "^1.0",
we do not need just the factory interfaces but a factory implementation. the correct thing to require is [psr/http-factory-implementation](https://packagist.org/providers/psr/http-factory-implementation)

2023-05-31 12:33 UTC, tacman commented on composer.json
> +        "psr/http-factory": "^1.0",
Hmm, while I follow what you're saying, I don't think I should be the one to change the code, as I don't understand it enough.

I'm just trying to get rid of deprecation messages, which are harder-than-expected to do in Symfony.

2023-05-31 14:14 UTC, dbu commented on composer.json
> +        "psr/http-factory": "^1.0",
fair enough. i will see when i get around to do it.

this is only a deprecation warning, not an error, nothing should break and the legacy factories will stay available for a couple of years, we won't just delete the repository.

2023-05-31 14:29 UTC, tacman commented on composer.json
> +        "psr/http-factory": "^1.0",
Yeah, this likely would be better as part of a 2.0 release -- where you could drop support for all EOL components, including PHP 7.  

Anyone needing the older code could keep using 1.7.  Then we can use type-hinting and method return types and all the other goodies that come with PHP 8.

Rector is a great tool for this.

2023-07-10 16:40 UTC, danepowell commented
@dbu @tacman is this something you plan to continue working on? I know the legacy library _probably_ won't disappear or suffer a vulnerability, but not everyone has the same risk tolerance. I for one will start getting pretty nervous soon 😄

2023-07-10 16:44 UTC, tacman commented
@danepowell realistically, I won't, as I don't understand it enough.  it's just one of the deprecation errors I'd like to get rid of, so I figured I'd report it here.

2023-07-11 06:53 UTC, dbu commented
the legacy library is done by php-http as well, as is the cache plugin. so it won't just disapear (or if we would somehow disapear the cache plugin would be gone as well - but i don't plan on disapearing ;-) ). there is no urgent risk here.

i don't have time right now to do the refactoring but would be happy to review if somebody has time to do it. i don't think it should be very complicated, as the interfaces are very similar and behave the same way.

2023-11-15 07:30 UTC, dbu commented
fixed in #87

2023-11-15 07:30 UTC, closed without merging